### ISSUE TITLE
Transfer this repo into the organization

### ISSUE THREAD

**Issue by Neustradamus** [q4z1/bbc_wec_site#77]
Dear @q4z1,

Can you remove the fork https://github.com/pokerth/bbc_wec_site and move this repository https://github.com/q4z1/bbc_wec_site into https://github.com/pokerth?

Thanks in advance.

**Comment by Neustradamus** [comment]
@q4z1: No answer, it has not been solved, can you reopen?

**Comment by q4z1** [comment]
It's not planned.
